version: "1.0"
stages:
  - "clone"
  - "build"
  - "push"
steps:
  clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "RoyGI/Build"
    stage: "clone"
  parallel_build:
    type: "parallel"
    stage: "build"
    steps:
      dotnet_build_v2_2:
        title: "Building DotNet 2.2 Image"
        type: "build"
        image_name: "dotnet_2_2"
        tag: "lasted"
        dockerfile: "Build/dotnet/2.2/sdk/Dockerfile"
      dotnet_build_v3_0:
        title: "Building DotNet 3.0 Image"
        type: "build"
        image_name: "dotnet_3_0"
        tag: "lasted"
        dockerfile: "Build/dotnet/3.0/sdk/Dockerfile"
      skaffold_build:
        title: "Building Skaffold Image"
        type: "build"
        image_name: "skaffold"
        tag: "lasted"
        dockerfile: "Build/skaffold/Dockerfile"
  parallel_push:
    type: "parallel"
    stage: "push"
    steps:
      push-dotnet-2_2:
        title: "Pushing dotnet 2.2 image to bintray"
        type: "push"
        image_name: "dotnet/sdk"
        registry: "mdocker"
        candidate: "${{dotnet_build_v2_2}}"
        tags:
          - "2.2"
      push-dotnet-3_0:
        title: "Pushing dotnet 3.0 image to bintray"
        type: "push"
        image_name: "dotnet/sdk"
        registry: "mdocker"
        candidate: "${{dotnet_build_v3_0}}"
        tags:
          - "3.0"
          - "latest"
      push-skaffold:
        title: "Pushing skaffold image to bintray"
        type: "push"
        image_name: "skaffold"
        registry: "mdocker"
        candidate: "${{skaffold_build}}"
        tags:
          - "latest"